apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zhweiliu/interview-infrastructure.git
      revision: main
      directories:
      - path: infrastructures/*
  template:
    metadata:
      name: 'infra-{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/zhweiliu/interview-infrastructure.git
        targetRevision: main
        path: infrastructures/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
            - .spec.template.spec.initContainers[].env[].valueFrom.resourceFieldRef.divisor
        - group: apps
          kind: StatefulSet
          jqPathExpressions:
            - .spec.volumeClaimTemplates[].apiVersion
            - .spec.volumeClaimTemplates[].kind
