apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql-data
provisioner: rancher.io/local-path
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
