apiVersion: v1
kind: Secret
metadata:
  name: metabase
data:
  MB_DB_TYPE: "postgres"
  MB_DB_HOST: "postgresql.database.svc.cluster.local"
  MB_DB_PORT: "5432"
  MB_DB_DBNAME: "metabase"
  MB_DB_USER: "metabase"
  MB_DB_PASS: "metabase"
