apiVersion: batch/v1
kind: CronJob
metadata:
  name: COMPONENT_NAME
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - prefect-work-pool
                  topologyKey: "kubernetes.io/hostname"
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - prefect-work-pool
          containers:
          - name: COMPONENT_NAME
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
